name: Upload package test

on:
  push:
    branches:
    - master
    paths:
    - 'packages/**'
  pull_request:
    paths:
    - 'packages/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: AIS install debs
      run: |
        sudo apt install -y rsync
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan -p ${SSH_PORT} -T 240 ${SSH_HOST} > ~/.ssh/known_hosts
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.AIS_USER }}
        SSH_KEY: ${{ secrets.AIS_SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.AIS_SERVER_IP }}
        SSH_PORT: ${{ secrets.AIS_PORT }}
    - name: rsync over ssh
      run: |
        mkdir -p ~/test
        echo "xxx" > ~/test/123.txt
        rsync -e 'ssh -p ${{ secrets.AIS_PORT }}' ~/test/  ${{ secrets.AIS_USER }}@${{ secrets.AIS_SERVER_IP }}:/var/www/ais-debs-staging
